model:
  static_image_mode: true
  model_complexity: 1
  smooth_landmarks: true
  enable_segmentation: false
  smooth_segmentation: true
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5
